{
  "formatVersion": "1.1",
  "component": {
    "group": "top.girlkisser",
    "module": "fractal",
    "version": "1.0.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fractal-1.0.2+1.21.1.jar",
          "url": "fractal-1.0.2+1.21.1.jar",
          "size": 37258,
          "sha512": "c2dd03655486f8f895b8868652cbdf2fa129559f0bdbc78c3575ece906d92df031c1a31fa617f3fcc4c7b93f556523121fa195edc4170b51d69232f79f35a25b",
          "sha256": "0a4601fbdb96e0c48b56aeeccfa7282c0790f7b2275f5e586418ddad471a69be",
          "sha1": "938b6a64fde62ba5c71ee580d04b4b6925c7d744",
          "md5": "af5ac706f5b96564d7cf6b216c8fba01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.2+1.21.1.jar",
          "url": "fractal-1.0.2+1.21.1.jar",
          "size": 37258,
          "sha512": "c2dd03655486f8f895b8868652cbdf2fa129559f0bdbc78c3575ece906d92df031c1a31fa617f3fcc4c7b93f556523121fa195edc4170b51d69232f79f35a25b",
          "sha256": "0a4601fbdb96e0c48b56aeeccfa7282c0790f7b2275f5e586418ddad471a69be",
          "sha1": "938b6a64fde62ba5c71ee580d04b4b6925c7d744",
          "md5": "af5ac706f5b96564d7cf6b216c8fba01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.2+1.21.1-sources.jar",
          "url": "fractal-1.0.2+1.21.1-sources.jar",
          "size": 23441,
          "sha512": "bbcd4c4cfe051613427208d91c08633e0ee55ec9cdc9d1a70e7e8da3a88984821c8fc9ba96a0778ff6e9c7f1a7e63c7661cf19630fe191e7aa5002c8392dcbac",
          "sha256": "4dd9b1d4936b035e4fdf8ba52c791a9d51f1080456e62ab7fd8c720b4b1aac21",
          "sha1": "633adbe2c44db5359f900e0e8f2df5859dd6e3c8",
          "md5": "9123d9019411062636336c4a357b2ac0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.2+1.21.1-javadoc.jar",
          "url": "fractal-1.0.2+1.21.1-javadoc.jar",
          "size": 164004,
          "sha512": "9bb3ad7c96b2d5d971af9844fa77eff68914121a8a0cddde3bb48d29d9a44dd8afc1189d51c3a2903e65ba6e7fc0e6cadb8baea02601b8c860b004810dfe3edd",
          "sha256": "cfe784cb866dac85b25721f343c5259acecd6ec2edaedab71f6efd66db89d7aa",
          "sha1": "bd0cb64eb515defb4e65fdb1bbfe501c32a39a32",
          "md5": "8981c7b5401faa1ea546a4156bac4de7"
        }
      ]
    }
  ]
}
