{
  "formatVersion": "1.1",
  "component": {
    "group": "top.girlkisser",
    "module": "fractal",
    "version": "1.0.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fractal-1.0.1+1.21.1.jar",
          "url": "fractal-1.0.1+1.21.1.jar",
          "size": 36787,
          "sha512": "2f3c3fcaff8685cb856c189978c26d103e9c16a25ccde560403765f8d6a47da63303354b9799d91e6378602a2b7eef114b319c661e5d1050a113479335e3db35",
          "sha256": "46e6e43e81fe7658e0ea2f1de8b9a20fa4f82194c80950dd3e3ed17312827a99",
          "sha1": "e83179acb41388357c1f4097045a42307aa7ad7e",
          "md5": "212305302bc1609af85551b25dc37c78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.1+1.21.1.jar",
          "url": "fractal-1.0.1+1.21.1.jar",
          "size": 36787,
          "sha512": "2f3c3fcaff8685cb856c189978c26d103e9c16a25ccde560403765f8d6a47da63303354b9799d91e6378602a2b7eef114b319c661e5d1050a113479335e3db35",
          "sha256": "46e6e43e81fe7658e0ea2f1de8b9a20fa4f82194c80950dd3e3ed17312827a99",
          "sha1": "e83179acb41388357c1f4097045a42307aa7ad7e",
          "md5": "212305302bc1609af85551b25dc37c78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.1+1.21.1-sources.jar",
          "url": "fractal-1.0.1+1.21.1-sources.jar",
          "size": 23173,
          "sha512": "b2f918ba35cb7572286211037f72765c993ee91d9d2dd40d901f0da5a9baa1d73fea2dc075abe51743da274e8e796c0012707f6a962a781919257147cf1a2a9d",
          "sha256": "221fa6b5052175992106ad78daedcda7f90a3dfe62fb086017c5e8ff90dd7b40",
          "sha1": "87ecec5775ee4099d37bb221c4fa94734b1e06fb",
          "md5": "c165d6bcd4a80d7e26d59caced0fe054"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.1+1.21.1-javadoc.jar",
          "url": "fractal-1.0.1+1.21.1-javadoc.jar",
          "size": 163431,
          "sha512": "2514bb6df3edde180cf55492297fc2335f9f12b398272ba91ea9209bc46ce7045ef1f103c1239caa05600837e6faf1fab8ca401f2bbda2de855ae7d77a119d16",
          "sha256": "b0df1934d0680c48b358c8d0bc95c6c1e8d4a735a81e3f5f17e754681287ad9f",
          "sha1": "8b11425b716b7aa8c112cc7edba5e0dacce7ef6d",
          "md5": "db3d67b4c637d9770b5ab9cded4b216e"
        }
      ]
    }
  ]
}
