{
  "formatVersion": "1.1",
  "component": {
    "group": "top.girlkisser",
    "module": "fractal",
    "version": "1.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fractal-1.0.0+1.21.1.jar",
          "url": "fractal-1.0.0+1.21.1.jar",
          "size": 36778,
          "sha512": "4bc52d4a33cd3a5969f4f52a8ee04699baffc94356039044eea2e4fca0ef0c894c196d2e8db124cb8b65bc97d71ebb0b14682ae52edd46b2c1a89847197b428a",
          "sha256": "900860025f307c1d2a4bf415c78f272881e9616b6aebf8f5dfdb8f79866ddd8a",
          "sha1": "fcc40e4b3ea4354222330b5489536d6767ebe1d2",
          "md5": "c005b40137dfb4661be4f5c5399cc1d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.0+1.21.1.jar",
          "url": "fractal-1.0.0+1.21.1.jar",
          "size": 36778,
          "sha512": "4bc52d4a33cd3a5969f4f52a8ee04699baffc94356039044eea2e4fca0ef0c894c196d2e8db124cb8b65bc97d71ebb0b14682ae52edd46b2c1a89847197b428a",
          "sha256": "900860025f307c1d2a4bf415c78f272881e9616b6aebf8f5dfdb8f79866ddd8a",
          "sha1": "fcc40e4b3ea4354222330b5489536d6767ebe1d2",
          "md5": "c005b40137dfb4661be4f5c5399cc1d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.0+1.21.1-sources.jar",
          "url": "fractal-1.0.0+1.21.1-sources.jar",
          "size": 23164,
          "sha512": "0f111d9bfff6c9f4b0af1c3f8c3b5169821c0195368561087ad953473a72e178205028a82a016e55a6e3319a9b271227eeba1702ca0a7edd0a698dadbd4dbf92",
          "sha256": "913839202359cc03cd261106f7c8df81d77913c312ce2b6befb34beffe6f84b2",
          "sha1": "549fe810c6b74f023d7262b2cccb607634863ff1",
          "md5": "ee90df859375027868132f0269fafc65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fractal-1.0.0+1.21.1-javadoc.jar",
          "url": "fractal-1.0.0+1.21.1-javadoc.jar",
          "size": 163446,
          "sha512": "b4816277d26b686c54896371eb065b60f47421b8b1879621fe1d8026d04a183579fa8e2b2b9458030b2a715fdeb35d5ba546945a15cc2f09ef933a5fc1a75f25",
          "sha256": "39693d194fb4378d436c5e753d793deba894e83d7d9b1abcc4639a703e1b76d0",
          "sha1": "483a1b3e8f3aec8b4deca9c94b4397c4ceb637cf",
          "md5": "132edb3ea545fa5ae4b3589bbc65f59b"
        }
      ]
    }
  ]
}
